intensive/about/urls.py
from django.urls import path

from about import views


app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

intensive/homepage/urls.py
from django.urls import path

from homepage import views


app_name = "homepage"

urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
]

intensive/intensive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include
from django.urls import path

import users.urls

urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include(users.urls)),
    path("auth/", include(django.contrib.auth.urls)),
    path("statistic/", include("statistic.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

intensive/users/urls.py
import django.contrib.auth.views
import django.urls

import users.forms
import users.views


app_name = "users"

urlpatterns = [
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
            authentication_form=users.forms.LoginForm,
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="users/logout.html"
        ),
        name="logout",
    ),
    django.urls.path(
        "password-change",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=django.urls.reverse_lazy("users:password-change-done"),
            form_class=users.forms.PasswordChangeForm,
        ),
        name="password-change",
    ),
    django.urls.path(
        "password-change-done",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password-change-done",
    ),
    django.urls.path(
        "password-reset",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=django.urls.reverse_lazy("users:password-reset-done"),
            form_class=users.forms.PasswordResetForm,
        ),
        name="password-reset",
    ),
    django.urls.path(
        "password-reset-done",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password-reset-done",
    ),
    django.urls.path(
        "password-reset-confirm/<uidb64>/<token>/",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password-reset-complite"
            ),
            form_class=users.forms.SetPasswordForm,
        ),
        name="password-reset-confirm",
    ),
    django.urls.path(
        "password-reset-complite",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complite.html"
        ),
        name="password-reset-complite",
    ),
    django.urls.path(
        "signup", users.views.SignupView.as_view(), name="signup"
    ),
    django.urls.path(
        "signup-done", users.views.SignupDoneView.as_view(), name="signup-done"
    ),
    django.urls.path(
        "activate/<str:username>",
        users.views.ActivateView.as_view(),
        name="activate",
    ),
    django.urls.path(
        "users-list", users.views.UsersListView.as_view(), name="users-list"
    ),
    django.urls.path(
        "user-detail/<int:user_id>",
        users.views.UserDetailView.as_view(),
        name="user-detail",
    ),
    django.urls.path(
        "profile", users.views.ProfileView.as_view(), name="profile"
    ),
    django.urls.path(
        "profile-done",
        users.views.ProfileDoneView.as_view(),
        name="profile-done",
    ),
    django.urls.path(
        "reactivate/<str:token>",
        users.views.ReactivateView.as_view(),
        name="reactivate",
    ),
]

intensive/users/models.py
import pathlib
import time

from django.contrib.auth.models import User, UserManager
from django.db import models
import django.utils.timezone
import sorl.thumbnail

import users.utils


class UserProfileManager(UserManager):
    @classmethod
    def normalize_email(cls, email):
        email = users.utils.normilize_email(email)
        return email

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .select_related("profile")
            .filter(is_active=True)
        )

    def birthdays(self):
        today = django.utils.timezone.localtime().date()
        return (
            self.get_queryset()
            .select_related("profile")
            .filter(
                profile__birthday__day=today.day,
                profile__birthday__month=today.month,
            )
            .only("profile__birthday", "username", "email")
        )

    def list_users(self):
        return (
            self.get_queryset()
            .select_related("profile")
            .only("username", "date_joined", "profile__id")
        )


class UserProxy(User):
    objects = UserProfileManager()

    class Meta:
        proxy = True


def get_user_media_path(instance, filename):
    creation_timestamp = int(time.time())
    filename = pathlib.Path(filename)
    basename, suffix = filename.stem, filename.suffix
    filename = f"{basename}_{creation_timestamp}{suffix}"
    media_path = pathlib.Path("users") / str(instance.user.id) / filename
    return media_path


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="profile"
    )
    birthday = models.DateField("дата рождения", blank=True, null=True)
    image = sorl.thumbnail.ImageField(
        "фото", upload_to=get_user_media_path, blank=True, null=True
    )
    coffee_count = models.PositiveIntegerField(
        "количество выпитых кофе", default=0
    )

    def get_thumbnail(self):
        if self.image:
            return sorl.thumbnail.get_thumbnail(
                self.image, "300x300", crop="center", quality=51
            )

    class Meta:
        verbose_name = "Дополнительное поле"
        verbose_name_plural = "Дополнительные поля"

intensive/users/forms.py
import betterforms.multiform
import django.contrib.auth.forms
from django.contrib.auth.models import User
import django.core.exceptions
import django.forms

import users.models


class LoginForm(django.contrib.auth.forms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"


class PasswordChangeForm(django.contrib.auth.forms.PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"


class PasswordResetForm(django.contrib.auth.forms.PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"


class SetPasswordForm(django.contrib.auth.forms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"


class SignupForm(django.contrib.auth.forms.UserCreationForm):
    email = django.forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    def clean_email(self):
        email = self.cleaned_data["email"]
        if email and User.objects.filter(email=email).exists():
            raise django.core.exceptions.ValidationError(
                "Пользователь с таким email уже существует"
            )
        return email

    class Meta:
        model = users.models.UserProxy
        fields = ["username", "email", "password1", "password2"]


class UserForm(django.forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = users.models.UserProxy
        fields = ("email", "first_name", "last_name")


class ProfileForm(django.forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = users.models.Profile
        fields = ("birthday", "image")
        widgets = {
            "birthday": django.forms.DateInput(
                attrs={"type": "date"}, format="%Y-%m-%d"
            ),
        }


class UserProfileMultiForm(betterforms.multiform.MultiModelForm):
    form_classes = {
        "user": UserForm,
        "profile": ProfileForm,
    }

intensive/users/views.py
import datetime

import axes.models
from django.conf import settings
import django.contrib.auth.mixins
import django.core.mail
from django.http import HttpResponseNotFound
import django.shortcuts
import django.template.loader
import django.urls
import django.utils.timezone
import django.views.generic
import jwt

import users.forms
import users.models


class SignupDoneView(django.views.generic.TemplateView):
    template_name = "users/signup_done.html"


class SignupView(django.views.generic.FormView):
    template_name = "users/signup.html"
    form_class = users.forms.SignupForm
    success_url = django.urls.reverse_lazy("users:signup-done")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = settings.IS_USER_ACTIVE
        activation_url = self.request.build_absolute_uri(
            django.urls.reverse(
                "users:activate", kwargs=dict(username=user.username)
            )
        )
        email = form.cleaned_data["email"]
        email_content = django.template.loader.render_to_string(
            "users/activate_email.html", {"activation_url": activation_url}
        )
        django.core.mail.send_mail(
            "Активация аккаунта.",
            email_content,
            django.conf.settings.FEEDBACK_EMAIL,
            [email],
            fail_silently=False,
        )
        user.save()
        profile = users.models.Profile(user=user)
        profile.save()
        return super().form_valid(form)


class ActivateView(django.views.generic.TemplateView):
    template_name = "users/activate_done.html"
    extra_context = {"success": False}

    def get(self, request, username):
        user = django.shortcuts.get_object_or_404(
            users.models.User, username=username
        )
        success = False
        status_code = 410
        timedelta_ago_joined = (
            user.date_joined - django.utils.timezone.localtime()
        )
        timedelta_ago_joined -= datetime.timedelta(
            microseconds=timedelta_ago_joined.microseconds
        )
        if timedelta_ago_joined <= datetime.timedelta(hours=12):
            user.is_active = True
            user.save()
            success = True
            status_code = 200

        self.extra_context = {"success": success}
        context = self.get_context_data()
        return self.render_to_response(context, status=status_code)


class UsersListView(django.views.generic.ListView):
    template_name = "users/users_list.html"
    model = users.models.UserProxy
    context_object_name = "users"

    def get(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise HttpResponseNotFound()
        return super().get(request, *args, **kwargs)


class UserDetailView(django.views.generic.DetailView):
    template_name = "users/user_detail.html"
    model = users.models.UserProxy
    context_object_name = "user"
    pk_url_kwarg = "user_id"

    def get(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return HttpResponseNotFound()
        return super().get(request, *args, **kwargs)


class ProfileDoneView(django.views.generic.TemplateView):
    template_name = "users/profile_done.html"


class ProfileView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.UpdateView,
):
    template_name = "users/profile.html"
    model = users.models.UserProxy
    form_class = users.forms.UserProfileMultiForm
    success_url = django.urls.reverse_lazy("users:profile-done")

    def get_object(self, queryset=None):
        return self.request.user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            instance={
                "user": self.request.user,
                "profile": self.request.user.profile,
            }
        )
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = self.get_form()
        context["forms"] = (
            form["user"],
            form["profile"],
        )
        return context


class ReactivateView(django.views.generic.TemplateView):
    template_name = "users/activate_done.html"
    extra_context = {"success": False}

    def get(self, request, token):
        try:
            reactivate_data = jwt.decode(
                token, settings.SECRET_KEY, algorithms="HS256"
            )
        except jwt.InvalidTokenError:
            success = False
            status_code = 401
        else:
            username = reactivate_data["username"]
            # axes.attempts.reset_user_attempts(request, credentials)
            axes.models.AccessAttempt.objects.filter(
                username=username
            ).delete()
            user = django.shortcuts.get_object_or_404(
                users.models.User, username=username
            )
            user.is_active = True
            user.save()
            success = True
            status_code = 200
        self.extra_context = {"success": success}
        context = self.get_context_data()
        return self.render_to_response(context, status=status_code)

intensive/templates/users/activate_email.html
{% autoescape off %}
Перейдите по ссылке, чтобы активировать учетную запись:

{{ activation_url }}
{% endautoescape %}

intensive/templates/users/login.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
  {% translate "Login" %}
{% endblock title %}
{% block content %}
  <div class="container my-5">
    <form method="post"
          enctype="multipart/form-data"
          class="needs-validation"
          novalidate>
      {% csrf_token %}
      {% for msg in messages %}<div class="alert alert-primary" role="alert">{{ msg }}</div>{% endfor %}
      {% include "includes/form.html" %}
      <button type="submit" class="btn btn-primary">Войти</button>
      <div class="mt-2">
        <a class="text-decoration-none" href="{% url 'users:password-reset' %}">Забыли пароль?</a>
        или 
        <a class="text-decoration-none" href="{% url 'users:signup' %}">Зарегистрироваться</a>
      </div>
    </form>
  </div>
{% endblock content %}

intensive/templates/users/logout.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
  {% translate "Logout" %}
{% endblock title %}
{% block content %}
  <div class="modal modal-sheet position-static d-block py-5"
       tabindex="-1"
       role="dialog"
       id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h1 class="modal-title fs-5">Выполнен выход</h1>
        </div>
        <div class="modal-body py-0">
          <p>Вы можете продолжить пользоваться сайтом или войти снова</p>
        </div>
        <div class="modal-footer flex-column border-top-0">
          <a href="{% url 'homepage:index' %}" class="btn btn-lg btn-primary w-100 mx-0">Продолжить</a>
          <a href="{% url 'users:login' %}" class="btn btn-lg btn-light w-100 mx-0 mb-2">Войти</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

intensive/templates/users/password_change.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
  {% translate "Login" %}
{% endblock title %}
{% block content %}
  <div class="container my-5">
    <form method="post"
          enctype="multipart/form-data"
          class="needs-validation"
          novalidate>
      {% csrf_token %}
      {% for msg in messages %}<div class="alert alert-primary" role="alert">{{ msg }}</div>{% endfor %}
      {% include "includes/form.html" %}
      <button type="submit" class="btn btn-primary">Сменить пароль</button>
      <p class="mt-2">
        Вернуться назад? <a href="{% url 'users:profile' %}" class="text-decoration-none">К профилю</a>
      </p>
    </form>
  </div>
{% endblock content %}

intensive/templates/users/password_change_done.html
{% extends "base.html" %}
{% block content %}
  <div class="modal modal-sheet position-static d-block py-5"
       tabindex="-1"
       role="dialog"
       id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h1 class="modal-title fs-5">Пароль успешно изменен</h1>
        </div>
        <div class="modal-body py-0">
          <p>Ваш пароль был изменен.</p>
        </div>
        <div class="modal-footer flex-column border-top-0">
          <a href="{% url 'homepage:index' %}"
             class="btn btn-lg btn-primary w-100 mx-0">На главную</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

intensive/templates/users/password_reset.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
  {% translate "Login" %}
{% endblock title %}
{% block content %}
  <div class="container my-5">
    <form method="post"
          enctype="multipart/form-data"
          class="needs-validation"
          novalidate>
      {% csrf_token %}
      {% for msg in messages %}<div class="alert alert-primary" role="alert">{{ msg }}</div>{% endfor %}
      {% include "includes/form.html" %}
      <button type="submit" class="btn btn-primary">Восстановить</button>
      <p class="mt-2">
        Вернуться назад? <a href="{% url 'users:login' %}" class="text-decoration-none">К логину</a>
      </p>
    </form>
  </div>
{% endblock content %}

intensive/templates/users/password_reset_complite.html
{% extends "base.html" %}
{% block content %}
  <div class="modal modal-sheet position-static d-block py-5"
       tabindex="-1"
       role="dialog"
       id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h1 class="modal-title fs-5">Восстановление пароля завершено</h1>
        </div>
        <div class="modal-body py-0">
          <p>Ваш пароль был успешно изменен. Теперь вы можете войти.</p>
        </div>
        <div class="modal-footer flex-column border-top-0">
          <a href="{% url 'users:login' %}"
             class="btn btn-lg btn-primary w-100 mx-0">Войти</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

intensive/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
  {% translate "Login" %}
{% endblock title %}
{% block content %}
  <div class="container my-5">
    <form method="post"
          enctype="multipart/form-data"
          class="needs-validation"
          novalidate>
      {% csrf_token %}
      {% for msg in messages %}<div class="alert alert-primary" role="alert">{{ msg }}</div>{% endfor %}
      {% include "includes/form.html" %}
      <button type="submit" class="btn btn-primary">Восстановить</button>
      <p class="mt-2">
        Вернуться назад? <a href="{% url 'users:login' %}" class="text-decoration-none">К логину</a>
      </p>
    </form>
  </div>
{% endblock content %}

intensive/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block content %}
  <div class="modal modal-sheet position-static d-block py-5"
       tabindex="-1"
       role="dialog"
       id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h1 class="modal-title fs-5">Письмо с инструкциями по восстановлению пароля отправлено</h1>
        </div>
        <div class="modal-body py-0">
          <p>
            Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты. Вы должны получить ее в ближайшее время.
          </p>
          <p>
            Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.
          </p>
        </div>
        <div class="modal-footer flex-column border-top-0">
          <a href="{% url 'homepage:index' %}"
             class="btn btn-lg btn-primary w-100 mx-0">На главную</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

intensive/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
  {% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}
  {% translate "Please go to the following page and choose a new password:" %}
  {% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'users:password-reset-confirm' uidb64=uid token=token %}
  {% endblock reset_link %}
  {% translate "Your username, in case you’ve forgotten:" %} {{ user.get_username }}
  {% translate "Thanks for using our site!" %}
  {% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
{% endautoescape %}

intensive/templates/users/profile.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
  {% translate "Login" %}
{% endblock title %}
{% block content %}
  <div class="container my-5">
    <form method="post"
          enctype="multipart/form-data"
          class="needs-validation"
          novalidate>
      {% csrf_token %}
      {% for msg in messages %}<div class="alert alert-primary" role="alert">{{ msg }}</div>{% endfor %}
      {% for form in forms %}
        {% include "includes/form.html" %}
      {% endfor %}
      <div class="mt-2">
        <a href="{% url 'users:password-change' %}"
           class="btn btn-primary">Изменить пароль</a>
      </div>
      <div class="mt-2">
        <a href="{% url 'homepage:coffee' %}" class="btn btn-info" role="button">Выпить кофе</a>
      </div>
      <button type="submit" class="btn btn-primary mt-2">Сохранить</button>
      <div class="mt-2">
        <a href="{% url 'users:logout' %}" class="text-decoration-none">Выйти</a>
      </div>
    </form>
  </div>
{% endblock content %}

intensive/templates/users/profile_done.html
{% extends "base.html" %}
{% block content %}
  <div class="modal modal-sheet position-static d-block py-5"
       tabindex="-1"
       role="dialog"
       id="modalSheet">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
          <h1 class="modal-title fs-5">Профиль изменен</h1>
        </div>
        <div class="modal-body py-0">
          <p>
            Изменения вступили в силу.
          </p>
        </div>
        <div class="modal-footer flex-column border-top-0">
          <a href="{% url 'homepage:index' %}"
             class="btn btn-lg btn-primary w-100 mx-0">На главную</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

intensive/templates/users/signup.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
  {% translate "Login" %}
{% endblock title %}
{% block content %}
  <div class="container my-5">
    <form method="post"
          enctype="multipart/form-data"
          class="needs-validation"
          novalidate>
      {% csrf_token %}
      {% for msg in messages %}<div class="alert alert-primary" role="alert">{{ msg }}</div>{% endfor %}
      {% include "includes/form.html" %}
      <button type="submit" class="btn btn-primary">Создать аккаунт</button>
    </form>
  </div>
{% endblock content %}

intensive/templates/users/users_list.html
{% extends "base.html" %}
{% block content %}
  <div class="container my-5">
    <div class="row row-cols-3 row-cols-md-2 g-4">
      {% for user in users %}
      <div class="col">
        <div class="card text-left">
          <h5 class="card-header text-center">{{ user.username }}</h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Почта: {{ user.email }}</li>
            <li class="list-group-item">Имя: {{ user.first_name }}</li>
            <li class="list-group-item">Фамилия: {{ user.last_name }}</li>
          </ul>    
          <div class="card-body">      
            <a href="{% url 'users:user-detail' user.id %}" class="btn btn-primary">Перейти к пользователю</a>
          </div>
          <div class="card-footer text-muted text-center">{{ user.date_joined }}</div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}