intensive/about/urls.py
from django.urls import path

from about import views


app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

intensive/homepage/urls.py
from django.urls import path

from homepage import views


app_name = "homepage"

urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
]

intensive/intensive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include
from django.urls import path

import users.urls

urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include(users.urls)),
    path("auth/", include(django.contrib.auth.urls)),
    path("statistic/", include("statistic.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

intensive/statistic/urls.py
import django.urls

import statistic.views

app_name = "statistic"

urlpatterns = [
    django.urls.path(
        "users/",
        statistic.views.UserListView.as_view(),
        name="users",
    ),
    django.urls.path(
        "user/<int:user_id>/",
        statistic.views.UserStatistic.as_view(),
        name="user-statistic",
    ),
    django.urls.path(
        "my_item_list/",
        statistic.views.UserItemStatisticListView.as_view(),
        name="my_item_list",
    ),
    django.urls.path(
        "item/<int:item_id>/",
        statistic.views.ItemStatistic.as_view(),
        name="item-statistic",
    ),
    django.urls.path(
        "item_list/",
        statistic.views.ItemStatisticListView.as_view(),
        name="item_list",
    ),
]

intensive/users/urls.py
import django.contrib.auth.views
import django.urls

import users.forms
import users.views


app_name = "users"

urlpatterns = [
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
            authentication_form=users.forms.LoginForm,
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="users/logout.html"
        ),
        name="logout",
    ),
    django.urls.path(
        "password-change",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=django.urls.reverse_lazy("users:password-change-done"),
            form_class=users.forms.PasswordChangeForm,
        ),
        name="password-change",
    ),
    django.urls.path(
        "password-change-done",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password-change-done",
    ),
    django.urls.path(
        "password-reset",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=django.urls.reverse_lazy("users:password-reset-done"),
            form_class=users.forms.PasswordResetForm,
        ),
        name="password-reset",
    ),
    django.urls.path(
        "password-reset-done",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password-reset-done",
    ),
    django.urls.path(
        "password-reset-confirm/<uidb64>/<token>/",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password-reset-complite"
            ),
            form_class=users.forms.SetPasswordForm,
        ),
        name="password-reset-confirm",
    ),
    django.urls.path(
        "password-reset-complite",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complite.html"
        ),
        name="password-reset-complite",
    ),
    django.urls.path(
        "signup", users.views.SignupView.as_view(), name="signup"
    ),
    django.urls.path(
        "signup-done", users.views.SignupDoneView.as_view(), name="signup-done"
    ),
    django.urls.path(
        "activate/<str:username>",
        users.views.ActivateView.as_view(),
        name="activate",
    ),
    django.urls.path(
        "users-list", users.views.UsersListView.as_view(), name="users-list"
    ),
    django.urls.path(
        "user-detail/<int:user_id>",
        users.views.UserDetailView.as_view(),
        name="user-detail",
    ),
    django.urls.path(
        "profile", users.views.ProfileView.as_view(), name="profile"
    ),
    django.urls.path(
        "profile-done",
        users.views.ProfileDoneView.as_view(),
        name="profile-done",
    ),
    django.urls.path(
        "reactivate/<str:token>",
        users.views.ReactivateView.as_view(),
        name="reactivate",
    ),
]

intensive/templates/includes/birthdays.html
{% if birthdays %}
<div class="container mt-3 alert alert-primary alert-dismissible fade show"
     role="alert">
  <table class="table table-bordered border-light caption-top">
    <caption>Сегодня день рождения у</caption>
    <thead>
      <tr>
        <th scope="col">username</th>
        <th scope="col">email</th>
      </tr>
    </thead>
    <tbody>
      {% for birthday_user in birthdays %}
        <tr>
          <td>{{ birthday_user.username }}</td>
          <td>{{ birthday_user.email }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <button type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"></button>
</div>
{% endif %}

intensive/templates/includes/footer.html
{% load static %}
{% load i18n %}
<footer class="container-fluid d-flex flex-wrap justify-content-between align-items-center py-3 border-top">
  <div class="col-md-4 d-flex align-items-center">
    <a href="{% url 'homepage:index' %}"
       class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
      <img src="{% static 'img/logo.svg' %}" alt="" width="50" height="44"/>
    </a>
    <span class="mb-3 mb-md-0 text-muted">© <span id="copyright-year"><noscript>{% now "Y" %}</noscript></span> Yozhic, Inc</span>
  </div>
</footer>
<script>
  const SECONDS = 1000;
  const MINUTES = 60;
  const HOURS = 60;
  const DAY = 24;
  var server_datetime = new Date({% now "U" %} * SECONDS);
  var local_datetime = new Date();
  var hours_delta = Math.abs(local_datetime - server_datetime) / SECONDS / MINUTES / HOURS / DAY;
  var datetime = hours_delta > 23 ? server_datetime : local_datetime;
  document.getElementById("copyright-year").innerHTML = datetime.getFullYear();
</script>

intensive/templates/includes/form.html
{% if form.errors %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
    </div>
  {% endfor %}
{% endif %}
{% for field in form %}
  <div class="mb-3">
    <label for="{{ field.id_for_label }}" class="form-label">
      {% if field.field.required %}<span>*</span>{% endif %}
      {{ field.label }}
    </label>
    <div class="{% if field.errors %}is-invalid{% endif %}">{{ field }}</div>
    <div id="{{ field.html_name }}HelpText" class="form-text">{{ field.help_text }}</div>
    {% if form.errors %}
      {% for error in field.errors %}<div class="invalid-feedback">{{ error|escape }}</div>{% endfor %}
    {% endif %}
  </div>
{% endfor %}

intensive/templates/includes/header.html
{% load static %}
{% load i18n %}
<header class="container-fluid d-flex flex-wrap justify-content-center py-3 border-bottom">
  <a href="{% url 'homepage:index' %}"
     class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
    <img src="{% static 'img/logo.svg' %}" alt="" width="50" height="44"/>
    <span class="mx-4 fs-4">{% translate "Yozhic" %}</span>
  </a>
  {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      <div class="btn-group">
        {% if request.user.is_authenticated %}
          <button class="btn btn-outline-primary dropdown-toggle"
                  type="button"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="true"
                  aria-expanded="false">
            {% if request.user.first_name %}
              {{ request.user.first_name }}
            {% else %}
              {{ request.user.email }}
            {% endif %}
          </button>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
            </li>
            {% if request.user.is_superuser %}
              <li>
                <a class="dropdown-item" href="{% url 'users:users-list' %}">Список пользователей</a>
              </li>
            {% endif %}
            <li>
              <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
            </li>
          </ul>
        {% else %}
          <button class="btn dropdown-toggle"
                  type="button"
                  data-bs-toggle="dropdown"
                  data-bs-auto-close="true"
                  aria-expanded="false">
            Аккаунт
          </button>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'users:login' %}">Вход</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'users:signup' %}">Создать аккаунт</a>
            </li>
          </ul>
        {% endif %}
      </div>
      <li class="nav-item">
        <a class="nav-link
                  {% if view_name == 'homepage:index' %}
                    active
                  {% endif %}"
           href="{% url 'homepage:index' %}">{% translate "Home" %}</a>
      </li>
      <div class="dropdown">
        <a class="btn btn-outline-primary
                  {% if view_name == 'catalog:item-list' %}
                    active
                  {% endif %}"
           role="button"
           href="{% url 'catalog:item-list' %}">{% translate "Catalog" %}</a>
        <button type="button"
                class="btn btn-outline-primary dropdown-toggle dropdown-toggle-split"
                data-bs-toggle="dropdown"
                aria-expanded="false">
        </button>
        <ul class="dropdown-menu">
          <li>
            <a class="dropdown-item
                      {% if view_name == 'catalog:new-items' %}
                        active
                      {% endif %}"
               href="{% url 'catalog:new-items' %}">{% translate "New" %}</a>
          </li>
          <li>
            <a class="dropdown-item
                      {% if view_name == 'catalog:friday-items' %}
                        active
                      {% endif %}"
               href="{% url 'catalog:friday-items' %}">{% translate "Friday" %}</a>
          </li>
          <li>
            <a class="dropdown-item
                      {% if view_name == 'catalog:unverified-items' %}
                        active
                      {% endif %}"
               href="{% url 'catalog:unverified-items' %}">{% translate "Unverified" %}</a>
          </li>
        </ul>
      </div>
      <div class="btn-group">
        <button class="btn btn-outline-primary dropdown-toggle"
                type="button"
                data-bs-toggle="dropdown"
                data-bs-auto-close="true"
                aria-expanded="false">
          Статистика
        </button>
        <ul class="dropdown-menu">
          <li>
            <a class="dropdown-item" href="{% url 'statistic:users' %}">Пользователи</a>
          </li>
          {% if request.user.is_authenticated %}
          <li>
            <a class="dropdown-item" href="{% url 'statistic:my_item_list' %}">Мои товары</a>
          </li>
          {% endif %}
          <li>
            <a class="dropdown-item" href="{% url 'statistic:item_list' %}">Список товаров</a>
          </li>
        </ul>
      </div>
      <li class="nav-item">
        <a class="nav-link
                  {% if view_name == 'about:about' %}
                    active
                  {% endif %}"
           href="{% url 'about:about' %}">{% translate "About" %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link
                  {% if view_name == 'feedback:feedback' %}
                    active
                  {% endif %}"
           href="{% url 'feedback:feedback' %}">{% translate "Feedback" %}</a>
      </li>
      {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">{% translate "Admin" %}</a>
        </li>
      {% endif %}
    </ul>
  {% endwith %}
</header>