intensive/about/urls.py
from django.urls import path

from about import views


app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

intensive/catalog/urls.py
import django.urls

from catalog import converters
from catalog import views


app_name = "catalog"

# N* according to ISO 80000-2
django.urls.register_converter(converters.PositiveInteger, "N*")

urlpatterns = [
    django.urls.path("", views.ItemListView.as_view(), name="item-list"),
    django.urls.path(
        "<int:item_id>", views.ItemDetailView.as_view(), name="item-detail"
    ),
    django.urls.re_path(
        r"^re/(?P<item_id>[1-9]\d*)/$",
        views.ItemDetailView.as_view(),
        name="re-item-detail",
    ),
    django.urls.path(
        "converter/<N*:item_id>/",
        views.ItemDetailView.as_view(),
        name="converter-item-detail",
    ),
    django.urls.path("new", views.NewItemView.as_view(), name="new-items"),
    django.urls.path(
        "friday", views.FridayItemsView.as_view(), name="friday-items"
    ),
    django.urls.path(
        "unverified",
        views.UnverifiedItemsView.as_view(),
        name="unverified-items",
    ),
]

intensive/homepage/urls.py
from django.urls import path

from homepage import views


app_name = "homepage"

urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
]

intensive/intensive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include
from django.urls import path

import users.urls

urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include(users.urls)),
    path("auth/", include(django.contrib.auth.urls)),
    path("statistic/", include("statistic.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

intensive/homepage/views.py
from django.http import HttpResponse
import django.views.generic

import catalog.models


class HomeView(django.views.generic.ListView):
    template_name = "homepage/home.html"
    queryset = catalog.models.Item.objects.on_main_page()
    context_object_name = "items"


class CoffeeView(django.views.generic.View):
    def get(self, request):
        if request.user.is_authenticated:
            request.user.profile.coffee_count += 1
            request.user.profile.save()
        return HttpResponse("<body>Я чайник</body>", status=418)

intensive/templates/homepage/home.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
  {% translate "Shop" %}
{% endblock title %}
{% block content %}
  <div class="z-index-n2 view intro-image">
    <div class="mask bg-success bg-opacity-50 d-flex justify-content-center align-items-center">
      <div class="container w-50">
        <div class="row">
          <div class="col-md-12 text-white text-center">
            <h1 class="fw-bold text-capitalize mb-3">{% translate "Hadgehog & Cat" %}</h1>
            <hr class="intro-hr w-50 mx-auto"/>
            <h5 class="mb-5 lead">{% translate "Best goods for best people" %}</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container my-4">
    <div class="row row-cols-1 row-cols-md-4 g-4">
      {% for item in items %}
        <div class="col">
          <a href="{% url 'catalog:item-detail' item.id %}"
             class="text-decoration-none">
            {% include "catalog/includes/item_card.html" %}
          </a>
        </div>
      {% empty %}
        <p>Товаров нема</p>
      {% endfor %}
    </div>
  </div>
{% endblock content %}