intensive/about/urls.py
from django.urls import path

from about import views


app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

intensive/intensive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include
from django.urls import path

import users.urls

urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include(users.urls)),
    path("auth/", include(django.contrib.auth.urls)),
    path("statistic/", include("statistic.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

intensive/statistic/urls.py
import django.urls

import statistic.views

app_name = "statistic"

urlpatterns = [
    django.urls.path(
        "users/",
        statistic.views.UserListView.as_view(),
        name="users",
    ),
    django.urls.path(
        "user/<int:user_id>/",
        statistic.views.UserStatistic.as_view(),
        name="user-statistic",
    ),
    django.urls.path(
        "my_item_list/",
        statistic.views.UserItemStatisticListView.as_view(),
        name="my_item_list",
    ),
    django.urls.path(
        "item/<int:item_id>/",
        statistic.views.ItemStatistic.as_view(),
        name="item-statistic",
    ),
    django.urls.path(
        "item_list/",
        statistic.views.ItemStatisticListView.as_view(),
        name="item_list",
    ),
]

intensive/statistic/views.py
import django.db.models
import django.shortcuts
import django.views.generic

import catalog.models
import rating.models
import users.models


class UserItemStatisticListView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.ListView,
):
    template_name = "statistic/my_item_list.html"
    context_object_name = "item_rating"

    def get_queryset(self):
        return rating.models.ItemRating.objects.statistic_list().filter(
            user_id=self.request.user.id
        )


class ItemStatisticListView(django.views.generic.ListView):
    template_name = "statistic/my_item_list.html"
    context_object_name = "item_rating"

    def get_queryset(self):
        return rating.models.ItemRating.objects.statistic_list()


class ItemStatistic(django.views.generic.TemplateView):
    template_name = "statistic/item_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object = catalog.models.Item.objects.only("name").get(
            pk=kwargs["item_id"]
        )
        context["item"] = self.object
        all_rating = (
            rating.models.ItemRating.objects.statistic_detail().filter(
                item=self.object
            )
        )
        max_min_avg = all_rating.aggregate(
            django.db.models.Max("score"),
            django.db.models.Min("score"),
            django.db.models.Avg("score"),
        )
        max_score = max_min_avg.get("score__max")
        min_score = max_min_avg.get("score__min")
        context["score"] = max_min_avg.get("score__avg")
        context["all_score"] = all_rating.count()
        if min_score == max_score:
            score = all_rating.filter(score=max_score).first()
            context["max_score"] = score
            context["min_score"] = score
        else:
            context["max_score"] = all_rating.filter(score=max_score).first()
            context["min_score"] = all_rating.filter(score=min_score).first()
        return context


class UserListView(django.views.generic.ListView):
    template_name = "statistic/user_list.html"
    queryset = users.models.UserProxy.objects.list_users()
    context_object_name = "users"


class UserStatistic(django.views.generic.TemplateView):
    template_name = "statistic/user_statistic.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get("user_id")
        user = django.shortcuts.get_object_or_404(
            users.models.UserProxy.objects.only("username"), pk=user_id
        )
        context["user"] = user
        max_min_avg = user.item_rating.aggregate(
            django.db.models.Max("score"),
            django.db.models.Min("score"),
            django.db.models.Avg("score"),
        )
        max_score = max_min_avg.get("score__max")
        min_score = max_min_avg.get("score__min")
        item = catalog.models.Item.objects.only("name")
        if min_score == max_score:
            rating_score = item.filter(ratings__score=max_score).first()
            context["best_rating"] = rating_score
            context["worst_rating"] = rating_score
        else:
            context["best_rating"] = item.filter(
                ratings__score=max_score
            ).first()
            context["worst_rating"] = item.filter(
                ratings__score=min_score
            ).first()
        context["rating_count"] = rating.models.ItemRating.objects.filter(
            user_id=user.id
        ).count()
        context["rating_mean"] = max_min_avg.get("score__avg")
        return context

intensive/templates/statistic/item_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
  {% translate "User" %}
{% endblock title %}
{% block content %}
  <div class="container my-5">
    <h1 class="d-flex align-items-center justify-content-center mb-5">{{ item.name }}</h1>
    <ul>
      <li>
        Средняя оценка: {{ score | default:'<span class="fw-light fst-italic">отсутствует</span>' }}
      </li>
      <li>
        Кол-во оценок: {{ all_score | default:'<span class="fw-light fst-italic">отсутствует</span>' }}
      </li>
      <li>
        Поставил максимальную оценку: {{ max_score.user.username | default:'<span class="fw-light fst-italic">отсутствует</span>' }}
      </li>
      <li>
        Поставил минимальую оценку: {{ min_score.user.username | default:'<span class="fw-light fst-italic">отсутствует</span>' }}
      </li>
    </ul>
  </div>
{% endblock content %}

intensive/templates/statistic/item_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
  {% translate "Users" %}
{% endblock title %}
{% block content %}
<div class="container my-4">
  <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for rating in item_rating %}
      <div class="col">
        <div class="card text-left">
          <h5 class="card-header text-center">{{ rating.item.name }}</h5>
           <div class="card-body">      
            <a href="{% url 'statistic:item-statistic' rating.item.id %}" class="btn btn-primary">Перейти к Товару</a>
          </div>
        </div>
      </div>
    {% empty %}
      <p>Юзеров нема</p>
    {% endfor %}
  </div>
</div>
{% endblock content %}

intensive/templates/statistic/my_item_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
  {% translate "Users" %}
{% endblock title %}
{% block content %}
<div class="container my-4">
  <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for rating in item_rating %}
      <div class="col">
        <div class="card text-left">
          <h5 class="card-header text-center">{{ rating.item.name }}</h5>
           <div class="card-body">      
            <a href="{% url 'statistic:item-statistic' rating.item.id %}" class="btn btn-primary">Перейти к Товару</a>
          </div>
        </div>
      </div>
    {% empty %}
      <p>Товаров нема</p>
    {% endfor %}
  </div>
</div>
{% endblock content %}

intensive/templates/statistic/user_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
  {% translate "Users" %}
{% endblock title %}
{% block content %}
<div class="container my-4">
  <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for user in users %}
      <div class="col">
        <div class="card text-left">
          <h5 class="card-header text-center">{{ user.username }}</h5>
           <div class="card-body">      
            <a href="{% url 'statistic:user-statistic' user.id %}" class="btn btn-primary">Перейти к пользователю</a>
          </div>
          <div class="card-footer text-muted text-center">{{ user.date_joined }}</div>
        </div>
      </div>
    {% empty %}
      <p>Юзеров нема</p>
    {% endfor %}
  </div>
</div>
{% endblock content %}

intensive/templates/statistic/user_statistic.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
  {% translate "User" %}
{% endblock title %}
{% block content %}
  <div class="container my-5">
    <h1 class="d-flex align-items-center justify-content-center mb-5">{{ user.username }}</h1>
    <ul>
      <li>
        Лучший товар: {{ best_rating | default:'<span class="fw-light fst-italic">отсутствует</span>' }}
      </li>
      <li>
        Худший товар: {{ worst_rating | default:'<span class="fw-light fst-italic">отсутствует</span>' }}
      </li>
      <li>
        Количество оценок: {{ rating_count | default:'<span class="fw-light fst-italic">отсутствует</span>' }}
      </li>
      <li>
        Средняя оценка: {{ rating_mean | default:'<span class="fw-light fst-italic">отсутствует</span>' }}
      </li>
    </ul>
  </div>
{% endblock content %}